// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtiedkxcyewlszkfojli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0aWVka3hjeWV3bHN6a2ZvamxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NTM1OTksImV4cCI6MjA3NDAyOTU5OX0.97mbESbGjO2lDuYCQih02ggZCY2nmucFEOw0EWK44JU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});